/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import bookstore.dbConnection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;

/**
 *
 * @author Minh Hieu
 */
public class frameLogin extends javax.swing.JFrame {

    /**
     * Creates new form frameLogin
     */
    public frameLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ĐĂNG NHẬP");
        setMinimumSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ĐĂNG NHẬP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(640, 170, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên đăng nhập:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 220, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật khẩu:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 260, 90, 30);

        txtTenDN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTenDN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenDNKeyPressed(evt);
            }
        });
        getContentPane().add(txtTenDN);
        txtTenDN.setBounds(620, 220, 240, 30);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(620, 260, 240, 30);

        btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap);
        btnDangNhap.setBounds(640, 330, 120, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\Project\\JAVA\\BOOKSTORE\\src\\Image\\background - Copy.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 960, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        String username = txtTenDN.getText();
        String password = String.valueOf(txtPassword.getPassword());
        
        if(username.equals("") || password.equals(""))
            JOptionPane.showConfirmDialog(rootPane, "Tên đăng nhập và mật khẩu không được để trống", "Nhắc nhở", 1);
        else{
            PreparedStatement pst = null;
            Connection conn = null;
            dbConnection a = new dbConnection();
            try{
                conn = a.getConnection();
                String sql = "SELECT * FROM NHANVIEN WHERE TENDN = ? AND MATKHAU = ?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, username);
                pst.setString(2, password);
                
                ResultSet resultSet  = pst.executeQuery();
                
                if(resultSet.next()){
                    MainForm frmMain = new MainForm();
                    frmMain.main(null);
                    frmMain.setTitle(username + " - Nhà sách Hoàng Hôn");
                    frameLogin.this.dispose();
                }
                else{
                    JOptionPane.showConfirmDialog(rootPane, "Sai tên đăng nhập hoặc mật khẩu", "Nhắc nhở", 1);
                    txtTenDN.setText("");
                    txtPassword.setText("");
                }
                
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String username = txtTenDN.getText();
        String password = String.valueOf(txtPassword.getPassword());
        
        if(username.equals("") || password.equals(""))
            JOptionPane.showConfirmDialog(rootPane, "Tên đăng nhập và mật khẩu không được để trống", "Nhắc nhở", 1);
        else{
            PreparedStatement pst = null;
            Connection conn = null;
            dbConnection a = new dbConnection();
            try{
                conn = a.getConnection();
                String sql = "SELECT * FROM NHANVIEN WHERE TENDN = ? AND MATKHAU = ?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, username);
                pst.setString(2, password);
                
                ResultSet resultSet  = pst.executeQuery();
                
                if(resultSet.next()){
                    MainForm frmMain = new MainForm();
                    frmMain.main(null);
                    frmMain.setTitle(username + " - Nhà sách Hoàng Hôn");
                    frameLogin.this.dispose();
                }
                else{
                    JOptionPane.showConfirmDialog(rootPane, "Sai tên đăng nhập hoặc mật khẩu", "Nhắc nhở", 1);
                    txtTenDN.setText("");
                    txtPassword.setText("");
                }
                
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtTenDNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDNKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String username = txtTenDN.getText();
        String password = String.valueOf(txtPassword.getPassword());
        
        if(username.equals("") || password.equals(""))
            JOptionPane.showConfirmDialog(rootPane, "Tên đăng nhập và mật khẩu không được để trống", "Nhắc nhở", 1);
        else{
            PreparedStatement pst = null;
            Connection conn = null;
            dbConnection a = new dbConnection();
            try{
                conn = a.getConnection();
                String sql = "SELECT * FROM NHANVIEN WHERE TENDN = ? AND MATKHAU = ?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, username);
                pst.setString(2, password);
                
                ResultSet resultSet  = pst.executeQuery();
                
                if(resultSet.next()){
                    MainForm frmMain = new MainForm();
                    frmMain.main(null);
                    frmMain.setTitle(username + " - Nhà sách Hoàng Hôn");
                    frameLogin.this.dispose();
                }
                else{
                    JOptionPane.showConfirmDialog(rootPane, "Sai tên đăng nhập hoặc mật khẩu", "Nhắc nhở", 1);
                    txtTenDN.setText("");
                    txtPassword.setText("");
                }
                
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }
        }
    }//GEN-LAST:event_txtTenDNKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
