package bookstore;
import bookstore.dbConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Minh Hieu
 */
public class frmSACH extends javax.swing.JFrame {

    DefaultTableModel tbn = new DefaultTableModel();
    
    public frmSACH() {
        initComponents();
        loadData();
        loadCBONXB();
        loadCBOTL();
    }
    
    public void loadCBONXB(){
        try{
            dbConnection a = new dbConnection();
            Connection conn = a.getConnection();
            PreparedStatement ps = conn.prepareStatement("select TENNXB from NHAXB");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                cboNXB.addItem(rs.getString("TENNXB"));
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }
    
    public void loadCBOTL(){
        try{
            dbConnection a = new dbConnection();
            Connection conn = a.getConnection();
            PreparedStatement ps = conn.prepareStatement("select TENTL from THELOAI");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                cboTHELOAI.addItem(rs.getString("TENTL"));
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }
    
    public void loadData(){
        try{
            dbConnection a = new dbConnection();
            Connection conn = a.getConnection();
            int number;
            Vector row, column = null;
            column = new Vector();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM SACH");
            ResultSetMetaData metadata = rs.getMetaData();
            number = metadata.getColumnCount(); //Tra ve so cot
            
            for(int i=1; i<=number; i++){
                column.add(metadata.getColumnName(i));//Lay tieu de cac cot
            }
            tbn.setColumnIdentifiers(column);
            
            while(rs.next()){
                row = new Vector();
                for(int i=1; i<=number; i++){
                    row.addElement(rs.getString(i));
                }
                tbn.addRow(row);
                tblSACH.setModel(tbn);
            }
            
            tblSACH.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
                @Override
                public void valueChanged(ListSelectionEvent e){
                    if(tblSACH.getSelectedRow() >= 0){
                        txtMASACH.setText(tblSACH.getValueAt(tblSACH.getSelectedRow(), 0) + "");
                        txtTENSACH.setText(tblSACH.getValueAt(tblSACH.getSelectedRow(), 1) + "");
                        txtTACGIA.setText(tblSACH.getValueAt(tblSACH.getSelectedRow(), 2) + "");
                        txtSL.setText(tblSACH.getValueAt(tblSACH.getSelectedRow(), 6) + "");
                        txtGIA.setText(tblSACH.getValueAt(tblSACH.getSelectedRow(), 7) + "");
                        txtDVT.setText(tblSACH.getValueAt(tblSACH.getSelectedRow(), 5) + "");
                        cboNXB.setSelectedItem(tblSACH.getModel().getValueAt(tblSACH.getSelectedRow(), 4)+"");
                        cboTHELOAI.setSelectedItem(tblSACH.getModel().getValueAt(tblSACH.getSelectedRow(), 3)+"");
                    }
                }
            });
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTENSACH = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTACGIA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGIA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnLUU = new javax.swing.JButton();
        btnCAPNHAT = new javax.swing.JButton();
        btnTHOAT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtMASACH = new javax.swing.JTextField();
        cboNXB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboTHELOAI = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDVT = new javax.swing.JTextField();
        btnXOA = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtMaTL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMaNXB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSACH = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sách");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập thông tin sách"));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tên sách:");

        txtTENSACH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tác giả:");

        txtTACGIA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NXB:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Số lượng:");

        txtSL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Giá:");

        txtGIA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("VNĐ");

        btnLUU.setIcon(new javax.swing.ImageIcon("E:\\Project\\JAVA\\BOOKSTORE\\src\\Image\\save-file-option.png")); // NOI18N
        btnLUU.setText("Lưu");
        btnLUU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLUUActionPerformed(evt);
            }
        });

        btnCAPNHAT.setIcon(new javax.swing.ImageIcon("E:\\Project\\JAVA\\BOOKSTORE\\src\\Image\\024-reload.png")); // NOI18N
        btnCAPNHAT.setText("Cập nhật");
        btnCAPNHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAPNHATActionPerformed(evt);
            }
        });

        btnTHOAT.setIcon(new javax.swing.ImageIcon("E:\\Project\\JAVA\\BOOKSTORE\\src\\Image\\power-button-off.png")); // NOI18N
        btnTHOAT.setText("Thoát");
        btnTHOAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHOATActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Mã sách:");

        txtMASACH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cboNXB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNXBActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Thể loại:");

        cboTHELOAI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboTHELOAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTHELOAIActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ĐVT:");

        txtDVT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnXOA.setIcon(new javax.swing.ImageIcon("E:\\Project\\JAVA\\BOOKSTORE\\src\\Image\\023-remove.png")); // NOI18N
        btnXOA.setText("Xoá");
        btnXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXOAActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon("E:\\Project\\JAVA\\BOOKSTORE\\src\\Image\\019-add.png")); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Mã TL:");

        txtMaTL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaTL.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Mã NXB:");

        txtMaNXB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLUU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCAPNHAT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXOA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTHOAT))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboTHELOAI, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtTENSACH, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(16, 16, 16)
                                .addComponent(txtMASACH, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(cboNXB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtGIA, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel1))
                                .addGap(0, 4, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(txtTACGIA)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTACGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtMASACH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtTENSACH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(cboNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboTHELOAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLUU, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCAPNHAT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXOA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTHOAT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tblSACH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tblSACH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        txtMASACH.setText("");
        txtTENSACH.setText("");
        txtTACGIA.setText("");
        txtSL.setText("");
        txtGIA.setText("");
        txtDVT.setText("");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLUUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLUUActionPerformed
        try{
            dbConnection a = new dbConnection();
            Connection conn = a.getConnection();
            PreparedStatement ps = conn.prepareStatement("insert into SACH values(?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, txtMASACH.getText());
            ps.setString(2, txtTENSACH.getText());
            ps.setString(3, txtTACGIA.getText());
            ps.setString(4, cboNXB.getSelectedItem().toString());
            ps.setString(5, cboTHELOAI.getSelectedItem().toString());
            ps.setString(6, txtDVT.getText());
            ps.setString(7, txtSL.getText());
            ps.setString(8, txtGIA.getText());
            ps.setString(9, txtMaTL.getText());
            ps.setString(10, txtMaNXB.getText());
            int chk = ps.executeUpdate();
            if(chk > 0){
                JOptionPane.showMessageDialog(this, "Them thanh cong!");
                tbn.setRowCount(0);
                loadData(); //truoc khi load data can load so cot ve 0 neu khong se load du lieu len bang them 1 lan nua 
            }else{
                
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnLUUActionPerformed

    private void btnCAPNHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAPNHATActionPerformed
        try{
            dbConnection a = new dbConnection();
            Connection conn = a.getConnection();
            PreparedStatement comm = conn.prepareStatement("update SACH set TENSACH=?, TACGIA=?, THELOAI=?, NXB=?, DVT=?, SL=?, DONGIA=?, MATL = ?, MANXB = ? where MASACH=?");
            comm.setString(8, txtMASACH.getText());
            comm.setString(1, txtTENSACH.getText());
            comm.setString(2, txtTACGIA.getText());
            comm.setString(3, cboTHELOAI.getSelectedItem().toString());
            comm.setString(4, cboNXB.getSelectedItem().toString());
            comm.setString(5, txtDVT.getText());
            comm.setString(6, txtSL.getText());
            comm.setString(7, txtGIA.getText());
            comm.setString(9, txtMaTL.getText());
            comm.setString(10, txtMaNXB.getText());
            comm.executeUpdate();
            tbn.setRowCount(0);
            loadData();
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnCAPNHATActionPerformed

    private void btnXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXOAActionPerformed
        try{
            dbConnection a = new dbConnection();
            Connection conn = a.getConnection();
            PreparedStatement comm = conn.prepareStatement("delete SACH where MASACH=?");
            comm.setString(1, tblSACH.getValueAt(tblSACH.getSelectedRow(), 0).toString());
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá quyển sách này?", "Xác nhận", 
                    JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                comm.executeUpdate();
                tbn.setRowCount(0);
                loadData();
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnXOAActionPerformed

    private void btnTHOATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHOATActionPerformed
        MainForm main = new MainForm();
        main.setVisible(true);
        frmSACH.this.dispose();
    }//GEN-LAST:event_btnTHOATActionPerformed

    private void cboTHELOAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTHELOAIActionPerformed
        try{
            dbConnection a = new dbConnection();
            Connection conn = a.getConnection();
            String fetch_row = "SELECT * FROM THELOAI WHERE TENTL = ?";
            PreparedStatement statement = conn.prepareStatement(fetch_row);
            statement.setString(1, (String)cboTHELOAI.getSelectedItem());
            ResultSet set = statement.executeQuery();
            while(set.next())
            {
                txtMaTL.setText(set.getString("MATL"));
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_cboTHELOAIActionPerformed

    private void cboNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNXBActionPerformed
        try{
            dbConnection a = new dbConnection();
            Connection conn = a.getConnection();
            String fetch_row = "SELECT * FROM NHAXB WHERE TENNXB = ?";
            PreparedStatement statement = conn.prepareStatement(fetch_row);
            statement.setString(1, (String)cboNXB.getSelectedItem());
            ResultSet set = statement.executeQuery();
            while(set.next())
            {
                txtMaNXB.setText(set.getString("MANXB"));
            }
        }catch(Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_cboNXBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSACH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSACH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCAPNHAT;
    private javax.swing.JButton btnLUU;
    private javax.swing.JButton btnTHOAT;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXOA;
    private javax.swing.JComboBox<String> cboNXB;
    private javax.swing.JComboBox<String> cboTHELOAI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSACH;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtGIA;
    private javax.swing.JTextField txtMASACH;
    private javax.swing.JTextField txtMaNXB;
    private javax.swing.JTextField txtMaTL;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTACGIA;
    private javax.swing.JTextField txtTENSACH;
    // End of variables declaration//GEN-END:variables
}
